project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ""
# base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: "/hsreplaynet/django/en/LC_MESSAGES/*.po"
    translation: "/hsreplaynet/django/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
    languages_mapping:
      locale_with_underscore:
        zh-CN: "zh_Hans"
        zh-TW: "zh_Hant"

  - source: "/archetypes/en/LC_MESSAGES/*.po"
    translation: "/archetypes/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
    languages_mapping:
      locale_with_underscore:
        zh-CN: "zh_Hans"
        zh-TW: "zh_Hant"

  - source: "/compositions/en/LC_MESSAGES/*.po"
    translation: "/compositions/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
    languages_mapping:
      locale_with_underscore:
        zh-CN: "zh_Hans"
        zh-TW: "zh_Hant"

  - source: "/hero_guides/en/LC_MESSAGES/*.po"
    translation: "/hero_guides/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
    languages_mapping:
      locale_with_underscore:
        zh-CN: "zh_Hans"
        zh-TW: "zh_Hant"

  - source: "/comp_guides/en/LC_MESSAGES/*.po"
    translation: "/comp_guides/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
    languages_mapping:
      locale_with_underscore:
        zh-CN: "zh_Hans"
        zh-TW: "zh_Hant"

  - source: "/anomaly_guides/en/LC_MESSAGES/*.po"
    translation: "/anomaly_guides/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
    languages_mapping:
      locale_with_underscore:
        zh-CN: "zh_Hans"
        zh-TW: "zh_Hant"

  - source: "/trinket_guides/en/LC_MESSAGES/*.po"
    translation: "/trinket_guides/%locale_with_underscore%/LC_MESSAGES/%original_file_name%"
    languages_mapping:
      locale_with_underscore:
        zh-CN: "zh_Hans"
        zh-TW: "zh_Hant"

  - source: "/hsreplaynet/frontend/en/*.json"
    translation: "/hsreplaynet/frontend/%locale%/%original_file_name%"
    languages_mapping:
      locale:
        en: "en"
        en-GB: "en-gb"
        fr: "fr"
        de: "de"
        ko: "ko"
        es-ES: "es"
        es-MX: "es-mx"
        ru: "ru"
        zh-TW: "zh-hant"
        zh-CN: "zh-hans"
        it: "it"
        pl: "pl"
        pt-BR: "pt-br"
        pt-PT: "pt"
        ja: "ja"
        th: "th"
